//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinGourlay.GenderEncoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColinGourlay.GenderEncoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aad	M	0
        ///Aadam	M	0
        ///Aadje	F	0
        ///Ådne	M	0
        ///Aadu	M	0
        ///Aaf	?F	0
        ///Aafke	F	0
        ///Aafke	?	0
        ///Aafkea	F	0
        ///Aafko	M	0
        ///Aage	M	0
        ///Åge	M	0
        ///Aagje	F	0
        ///Aagot	F	0
        ///Ågot	F	0
        ///Aagoth	F	0
        ///Ågoth	F	0
        ///Åke	M	0
        ///Aalbert	M	0
        ///Aalderich	M	0
        ///Aalderk	M	0
        ///Aaldrik	M	0
        ///Aale	M	0
        ///Aaliyah	F	1
        ///Aalke	F	0
        ///Aalt	M	0
        ///Aaltien	F	0
        ///Aaltinus	M	0
        ///Aaltje	F	0
        ///Aaltsje	F	0
        ///Aamir	M	0
        ///Aant	?F	0
        ///Aapeli	M	0
        ///Aapo	M	0
        ///Aappo	M	0
        ///Aard	M	0
        ///Aare	M	0
        ///Aarent	M	0
        ///Aarjan	M	0
        ///Aarne	M	0
        ///Aarni	M	0
        ///Aarno	M	0
        ///Aarnoud	M	0
        ///Aarnout	M	0
        ///Aaro	M	0
        ///Aaron [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenderCodingNames {
            get {
                return ResourceManager.GetString("GenderCodingNames", resourceCulture);
            }
        }
    }
}
